---
name: Build and Publish Docker Image
permissions:
  packages: write
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: System Dependencies for Testing
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip
      - name: Setup Test Environment
        run: |
           python3 -m venv env
           ./env/bin/pip install -U pip
           ./env/bin/pip install .[test]
           ./env/bin/pytest
  build_and_push:
    runs-on: ubuntu-latest
    needs: [tests]
    # TODO: if: startsWith(github.ref, 'refs/tags/release/')
    steps:
      - name: System Dependencies for Packaging
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip install --upgrade pip
          sudo pip install yq
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment
        run: |
          echo "APP_VERSION=$(tomlq -r .project.version pyproject.toml)" >> $GITHUB_ENV
          echo "APP_DESC=$(tomlq -r .project.description pyproject.toml)" >> $GITHUB_ENV
      - name: Build Image
        run: >
          docker build
          --build-arg "APP_VERSION=${APP_VERSION}"
          --build-arg "APP_DESC=${APP_DESC}"
          -t "ghcr.io/${GITHUB_REPOSITORY}:${APP_VERSION}"
          .
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push Docker Image
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${APP_VERSION}"
